/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function initialize(): object
export function sendCommand(command: string, arg: string, senderObj: object, callback: (...args: any[]) => any): void
